version: "3"
services:
  app:
    container_name: cardoc_api
    environment:
      TZ: "Asia/Seoul"
      SPRING_PROFILES_ACTIVE : real
    restart: always
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - cardoc_db

  cardoc_db:
    container_name: cardoc_database
    image: mysql
    environment:
      TZ: "Asia/Seoul"
      MYSQL_DATABASE: cardoc_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306

  nginx:
    container_name: cardoc_nginx
    image: nginx
    environment:
      TZ: "Asia/Seoul"
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app