spring:
  datasource:
    url: jdbc:mysql://cardoc_db:3306/cardoc_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

jwt:
  secret-key: cardoc-wanted-preonboarding-2222