version: "3"
services:
  cardoc_db:
    container_name: cardoc_database
    image: mysql
    environment:
      MYSQL_DATABASE: cardoc_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
    - 3306:3306
